# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naturalUser', '0002_userfavorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavorite',
            name='nat_user',
        ),
        migrations.RemoveField(
            model_name='userfavorite',
            name='ong',
        ),
        migrations.DeleteModel(
            name='UserFavorite',
        ),
    ]
